<?php
// Retrieve order
$_order = new Mage_Sales_Model_Order();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$_order->loadByIncrementId($orderId);

//var_dump($_order->getAllItems());
$items_description = '';

$items = $_order->getAllItems();

foreach($items as $item){
	
	$items_description .= $item->getName();
	
	}
	
	//var_dump($items_description);

$encryption_keyword = Mage::getStoreConfig('payment/paymentmethod/encryption_keyword',Mage::app()->getStore());
$payment_gateway_url = Mage::getStoreConfig('payment/paymentmethod/payment_gateway_url',Mage::app()->getStore());
$language = Mage::getStoreConfig('payment/paymentmethod/language',Mage::app()->getStore());
$currency = Mage::getStoreConfig('payment/paymentmethod/currency',Mage::app()->getStore());
$merchant_id = Mage::getStoreConfig('payment/paymentmethod/merchant_id',Mage::app()->getStore());

//exit();
?>
<form name="cashupaymentform" action="<?php echo $payment_gateway_url;?>" method="post">
<input type="hidden" name="merchant_id" value="<?php echo $merchant_id;?>">
<input type="hidden" name="token" value="<?php echo md5($merchant_id.':'.round($_order->getBaseGrandTotal(),2).':'.$currency.':'.$encryption_keyword);?>">
<input type="hidden" name="display_text" value="<?php echo $items_description;?>">
<input type="hidden" name="currency" value="<?php echo $currency;?>">
<input type="hidden" name="amount" value="<?php echo round($_order->getBaseGrandTotal(),2);?>">
<input type="hidden" name="language" value="<?php echo $language;?>">
<input type="hidden" name="session_id" value="asdasd-234-asdasd">
<input type="hidden" name="txt1" value="<?php echo $orderId; ?>">
</form>
<script type="text/javascript">
document.cashupaymentform.submit();
</script>
